### ISSUE TITLE
constructible versus constructable

### ISSUE THREAD

**Issue by Lonniebiz** [WICG/construct-stylesheets#96] opened 2019-07-15 08:07 UTC
Which word is correct, constructible or constructable?

https://wikidiff.com/content/constructable-vs-constructible-whats-difference-0

All stylesheets can be constructed, the essence of this feature is that you can reference the stylesheet, within the shadowDOM, efficiently, like you would an object or an array: assign-by-reference.

I don't like the name, but I do appreciate the concept and look forward to it being implemented in all browsers.

**Comment by domenic** [comment] 2019-07-15 15:01
Dupe of #90.

**Closed as completed** 2019-07-15 18:51 UTC
