### ISSUE TITLE
replaceSync() clears CSS rules before throwing NotAllowedError

### ISSUE THREAD

**Issue by nordzilla** [WICG/construct-stylesheets#101] opened 2019-12-12 20:45 UTC
The [spec description](https://wicg.github.io/construct-stylesheets/#dom-cssstylesheet-replacesync) for `replaceSync(text)` lists on **step 3)** that the _sheet_'s CSS rules should be set to an empty list. 

This happens before **step 5)** where we might still throw a `NotAllowedError` if the parsed `text` contains any `@import` rules. 

This would lead to behavior where a sheet that already has existing rules calls `replaceSync(text)`, throws a `NotAllowedError`, and still has its rules cleared to nothing. 

Is this the intended behavior? As a user, I would expect that if a `NotAllowedError` is thrown, then the existing rules would remain unaffected.

**Comment by tabatkins** [comment] 2019-12-12 23:25
I don't think this is intended behavior; if we're going to reject the operation it shouldn't have any side effects.

**Comment by nordzilla** [comment] 2019-12-13 00:34
It seems reasonable to me that **Step 3)** can be removed all together. The current **Step 6)** assigns the _sheet_'s rules to the parsed rules, which will already be empty if the parse failed, as specified in **Step 4)**.

**Comment by rakina** [comment] 2019-12-13 13:29
Interesting, thanks for noticing. I made https://github.com/WICG/construct-stylesheets/pull/103 to fix the spec, and looks like the impl in Blink needs updating too. Thanks!

**Comment by rakina** [comment] 2019-12-16 09:19
Spec change merged, Blink bug filed. https://bugs.chromium.org/p/chromium/issues/detail?id=1034414

**Closed as completed by rakina** 2019-12-16 09:19 UTC
